version: '3'
services:
  phpfpm:
    container_name: ci-php-fpm
    image: arturslogins/ci-php-fpm:7.3.12
    ports:
      - 3000:3000
    volumes:
      - ./:/var/www/html
    command: php -S="0.0.0.0:3000" -t="/var/www/html"